name: Android CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Do tests
      run: ./gradlew test
  
  android_instrument_tests:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Do android tests
      if: ${{ always() }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        script: ./gradlew connectedCheck
