name: Android CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Do tests
      run: ./gradlew test
    - name: Do android tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace
