name: Android CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - 
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Do tests
      run: ./gradlew test
      
    - name: Do android tests
      if: ${{ always() }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        script: ./gradlew connectedAndroidTest
