name: Android CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.4.0

    - name: Set up JDK 11
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 11

    - uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

  unit_tests:
    name: Run unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.4.0
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Do tests
      run: ./gradlew test
      
    - uses: actions/upload-artifact@v2
      with:
        name: JUnit test results
        path: ./build/reports/

  instrumentation_tests:
    name: Run instrumentation tests
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.4.0

      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: 26
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ui-test-report
          path: ./build/reports/

          
  apk:
    name: Generate APK
    needs: [build, unit_tests, instrumentation_tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
