name: Android CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  
  unit_tests:
    runs-on: macOS-latest
    needs: [build]
    steps:
    - name: Unit tests
      run: ./gradlew test
  
  instrumentation_tests:
    runs-on: macOS-latest
    needs: [build]
    steps:
    - name: Android Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        script: ./gradlew connectedCheck
        
