name: 'Hello World'
runs:
  using: "composite"
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
